version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  groups:
    dev-dependencies:
      dependency-type: "development"
      update-types:
        - "minor"
        - "patch"
  schedule:
    interval: weekly
    time: "03:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  versioning-strategy: increase
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
